language: csharp
mono: none
dotnet: 2.1.300
script:
  - dotnet restore
  - dotnet test *Tests

before_deploy:
  - cd *ConsoleApp
  - ./publish.sh
  - zip -rmDT0 github-ext.linux-x64.zip linux-x64
  - zip -rmDT0 github-ext.win-x64.zip win-x64

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master
    target-branch: gh-pages
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
    file_glob: true
    file: *ConsoleApp/publish/*.zip
    name: v$TRAVIS_TAG
    draft: true
