language: csharp
mono: none
dotnet: 2.1.300
branches:
  only:
  - master
script:
  - dotnet restore
  - dotnet build
  - dotnet test *Tests --no-build

before_deploy:
  - if [[ -n $TRAVIS_TAG ]]; then ./publish.sh $TRAVIS_TAG.$TRAVIS_BUILD_NUMBER; fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master
    target-branch: gh-pages
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
    file_glob: true
    file: ./*ConsoleApp/publish/*.zip
    name: v$TRAVIS_TAG
    draft: true
